# Generated by Django 3.2.7 on 2021-10-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8, verbose_name='期数')),
                ('title', models.CharField(max_length=32, verbose_name='网站标题')),
                ('href', models.CharField(max_length=128, verbose_name='网站链接')),
                ('slogan', models.CharField(max_length=64, verbose_name='网站简介')),
                ('kind_name', models.CharField(max_length=16, verbose_name='分类名称')),
                ('star', models.CharField(max_length=8, verbose_name='星标')),
            ],
        ),
        migrations.CreateModel(
            name='WebVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16, verbose_name='数据版本号')),
            ],
        ),
    ]
