# Generated by Django 3.2.7 on 2021-10-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='kind',
            field=models.CharField(max_length=8, verbose_name='期数分类'),
        ),
        migrations.AlterField(
            model_name='web',
            name='star',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='星标'),
        ),
    ]
