# Generated by Django 3.2.7 on 2021-10-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_mail_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='content',
            field=models.TextField(max_length=1024, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='ip',
            field=models.TextField(max_length=1024, verbose_name='IP'),
        ),
    ]
