# Generated by Django 3.2.7 on 2021-10-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20211009_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='ip',
        ),
    ]
