# Generated by Django 3.2.7 on 2021-10-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_mail_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=256, verbose_name='网站链接')),
                ('content', models.TextField(max_length=256, verbose_name='网站描述')),
            ],
        ),
    ]
