# Generated by Django 3.2.7 on 2021-10-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_webinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='web_title',
            field=models.CharField(default=1, max_length=64, verbose_name='网站标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='title',
            field=models.CharField(max_length=64, verbose_name='页面标题'),
        ),
    ]
